"""Indexes for the bounded persistent catalog activity feed.

Revision ID: 0033_catalog_activity
Revises: 0032_match_live
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0033_catalog_activity"
down_revision: str | None = "0032_match_live"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_canonical_products_activity",
        "canonical_products",
        ["created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_offer_events_activity", "offer_events", ["detected_at", "id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_offer_events_activity", table_name="offer_events")
    op.drop_index("ix_canonical_products_activity", table_name="canonical_products")
    # ### end Alembic commands ###
